<a href="https://colab.research.google.com/github/drippystacie/codeoffuture/blob/main/dz16ml1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Найдите транспонированную матрицу A, если:
a) A=1 54 1 6 2 7
b) A=1 7 8 4 2 9 5 6 3

In [ ]:
import numpy as np
A = np.array([[1, 54, 1], [6, 2, 7]])
A_transposed = np.transpose(A)
print(A_transposed)

[[ 1  6]
 [54  2]
 [ 1  7]]


In [ ]:
import numpy as np
A = np.array([[1, 7, 8], [4, 2, 9], [5, 6, 3]])
A_transposed = np.transpose(A)
print(A_transposed)

[[1 4 5]
 [7 2 6]
 [8 9 3]]


Если возможно, найдите матричное произведение матриц A, B, если:
a) A=1 2 4 5 7 8 , B=1 1 0 0 1 1 1 0 1
b) A=1 2 3 4 5 6 7 8 9 , B=1 1 0 0 1 1 1 0 1

In [ ]:
import numpy as np
A = np.array([[1, 2, 4], [5, 7, 8]])
B = np.array([[1, 1, 0], [0, 1, 1], [1, 0, 1]])
AB = np.dot(A, B)
print(AB)

[[ 5  3  6]
 [13 12 15]]


In [ ]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 1, 0], [0, 1, 1], [1, 0, 1]])
AB = np.dot(A, B)
print(AB)

[[ 4  3  5]
 [10  9 11]
 [16 15 17]]


Вычислите оптимальный вектор весов по формуле w=XTX-1XTY=XTYXTX. Для этого сформируйте матрицы X, Y, а потом выполните все необходимые операции, подставляя их в формулу, кроме взятия обратной матрицы. Ответ представить в виде w=АВ, где A=XTY, B=XTX. Проделать для следующего датасета:

Номер дома
Кол-во спален
Площадь, м2
Цена, тыс. $
1
1
145
80
2
2
163
170
3
3
240
100
4
3
350
220
5
4
421
200
6
4
397
270
7
5
620
500








In [ ]:
import pandas as pd
import numpy as np
data = {
    'dom': [1, 2, 3, 4, 5, 6, 7],
    'spalni': [1, 2, 3, 3, 4, 4, 5],
    'ploshad': [145, 163, 240, 350, 421, 397, 620],
    'cena': [80, 170, 100, 220, 200, 270, 500]
}
df = pd.DataFrame(data)
X = df[['spalni', 'ploshad']].values
Y = df['cena'].values
A = np.dot(X.T, Y)
B = np.dot(X.T, X)
A, B

(array([  5760, 641700]),
 array([[    80,   8613],
        [  8613, 946944]]))