<a href="https://colab.research.google.com/github/drippystacie/codeoffuture/blob/main/dzlesson2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Создайте вектор из 100 случайных чисел от 1 до 10, по аналогии, как был создан вектор из 5 случайных чисел от 1 до 2: arr = np.random.randint(1, 2, size=5). Посчитайте, не используя циклы, какой процент элементов в векторе больше 7.


In [1]:
import numpy as np
a = np.random.randint(1, 11, size=100)
count = np.sum(a > 7)
b = count / len(a) * 100
print("Процент элементов в векторе больше 7:", b)

Процент элементов в векторе больше 7: 34.0


Проведите опыт из предыдущей задачи 1000 раз, а именно, создание вектора и подсчёт процента элементов, больших 7. Какая часть полученных результатов равно 20 %?


In [2]:
results = []
for i in range(1000):
    a = np.random.randint(1, 11, size=100)
    count = np.sum(a > 7)
    b = count / len(a) * 100
    results.append(b)
    count_20 = results.count(20)
b1 = count_20 / len(results) * 100
print("Часть результатов, равных 20 %:", b1)

Часть результатов, равных 20 %: 0.6


Создайте матрицу numpy 10 x 10, где каждая строка будет выглядеть, как 1, 2, 3, 4, 5, 6, 7, 8, 9, 10. Желательно не использовать циклы.


In [6]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.tile(a, (10, 1))
print(b)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


Не используя циклы, найдите суммы элементов матрицы в каждом столбце.


In [7]:
import numpy as np
a = np.tile(np.arange(1, 11), (10, 1))
summa = np.sum(a, axis=0)
print(summa)

[ 10  20  30  40  50  60  70  80  90 100]
